### ISSUE TITLE
Segmentation fault while compiling

### ISSUE THREAD

**Issue by lighth7015** [Shad0w1nk/snes-sdk#2]
Hi,

While trying to build the SDK, I receive a segmentation fault in `816-tcc`-
```
[robert.butler@mc01 snes-sdk]$ make
cd wla_dx && make PREFIX=/usr/local/snes-sdk
make[1]: Entering directory '/home/HMNC/robert.butler/github/snes-sdk/wla_dx'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/HMNC/robert.butler/github/snes-sdk/wla_dx'
cd wla_dx/wlalink && make PREFIX=/usr/local/snes-sdk
make[1]: Entering directory '/home/HMNC/robert.butler/github/snes-sdk/wla_dx/wlalink'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/HMNC/robert.butler/github/snes-sdk/wla_dx/wlalink'
cd wla_dx/wlab && make PREFIX=/usr/local/snes-sdk
make[1]: Entering directory '/home/HMNC/robert.butler/github/snes-sdk/wla_dx/wlab'
cc  main.o -o wlab ; strip wlab
make[1]: Leaving directory '/home/HMNC/robert.butler/github/snes-sdk/wla_dx/wlab'
make[1]: Entering directory '/home/HMNC/robert.butler/github/snes-sdk/tcc-65816'
make[1]: '816-tcc' is up to date.
make[1]: Leaving directory '/home/HMNC/robert.butler/github/snes-sdk/tcc-65816'
cd libs && make PREFIX=/usr/local/snes-sdk
make[1]: Entering directory '/home/HMNC/robert.butler/github/snes-sdk/libs'
../tcc-65816/816-tcc  -I. -I./../tcc-65816/include -o libc_c.pasm -c libc_c.c
make[1]: *** [Makefile:5: libc_c.pasm] Segmentation fault (core dumped)
make[1]: Leaving directory '/home/HMNC/robert.butler/github/snes-sdk/libs'
make: *** [Makefile:18: libs] Error 2
```

**Comment by lighth7015** [comment]
Also, trying to do a clean build, I receive this (probably related)-
```
make[1]: Leaving directory '/home/HMNC/robert.butler/github/snes-sdk/tcc-65816'
cd libs && make PREFIX=/usr/local/snes-sdk
make[1]: Entering directory '/home/HMNC/robert.butler/github/snes-sdk/libs'
../wla_dx/wla-65816 -io crt0_snes.asm crt0_snes.obj
python ../tcc-65816/816-opt.py libm_c.pasm >libm_c.asm
Traceback (most recent call last):
  File "../tcc-65816/816-opt.py", line 15, in <module>
    text_raw = open(sys.argv[1],'r').readlines()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 2749: invalid start byte
make[1]: *** [Makefile:10: libm_c.asm] Error 1
```

**Comment by SeanRamey** [comment]
I get this same issue.
```make[1]: Leaving directory '/home/sean/code/snes-sdk/tcc-65816'
cd libs && make PREFIX=/usr/local/snes-sdk
make[1]: Entering directory '/home/sean/code/snes-sdk/libs'
../wla_dx/wla-65816 -io crt0_snes.asm crt0_snes.obj
../tcc-65816/816-tcc  -I. -I../tcc-65816/include -o libm_c.pasm -c libm_c.c
make[1]: *** [Makefile:5: libm_c.pasm] Segmentation fault (core dumped)
make[1]: *** Deleting file 'libm_c.pasm'
make[1]: Leaving directory '/home/sean/code/snes-sdk/libs'
make: *** [Makefile:14: libs] Error 2```
